// apps/battery/angular/src/app/home.component.ts
import { Component, OnInit, inject, NgZone } from '@angular/core';
import { checkBatteryLevel, listenForBatteryChanges } from '@stackblitz/nativescript-battery';

const formatMessage = (level) => `The Battery Level is: ${level}%`;

@Component({
  selector: 'ns-home',
  templateUrl: './home.component.html',
})
export class HomeComponent implements OnInit {
  level: number;
  isListening = false;
  ngZone = inject(NgZone);

  ngOnInit() {
    this.updateBatteryLevel();
  }

  async updateBatteryLevel() {
    const value = await checkBatteryLevel();
    this.updateLevel(value);
    alert(formatMessage(value));
  }

  async toggleListenForChanges() {
    this.isListening = listenForBatteryChanges((value) => {
      this.updateLevel(value);
    });
    if (this.isListening) {
      // update view binding right away
      const value = await checkBatteryLevel();
      this.updateLevel(value);
    }
  }

  private updateLevel(value: number) {
    this.ngZone.run(() => {
      this.level = value;
    });
  }
}

<ActionBar title="NativeScript is pretty cool!"> </ActionBar>

<StackLayout class="p-20">
  <Label text="The Battery Level is:" class="h1 text-center"></Label>
  <Label [text]="level ? level + '%' : '---'" class="h2 text-center"></Label>
  <Button [text]="isListening ? 'Stop Listening to Battery Changes' : 'Listen for battery changes'" class="action-btn" (tap)="toggleListenForChanges()"></Button>
</StackLayout>

// apps/battery/svelte/src/components/Home.svelte
<page>
    <actionBar title="NativeScript is pretty cool!" />

    <stackLayout class="p-5">
        <label text="The Battery Level is:" class="text-xl font-bold text-center" />
        <label text={level ? level + '%' : '---'} class="text-2xl text-center mt-2" />
        <button
            text={isListening
                ? 'Stop Listening to Battery Changes'
                : 'Listen for battery changes'}
            class="py-2 px-2 mt-4 rounded-full bg-blue-400 text-lg text-white"
            on:tap={toggleListenForChanges}
            />
        <image
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/1200px-Svelte_Logo.svg.png"
            width="200"
            class="mt-5"
            />
    </stackLayout>
</page>
  
<script lang="ts">
  import {
    checkBatteryLevel,
    listenForBatteryChanges,
  } from '@stackblitz/nativescript-battery';

  const formatMessage = (level: number) => `The Battery Level is: ${level}%`;

  let level: number;
  let isListening = false;

  async function updateBatteryLevel() {
    const value = await checkBatteryLevel();
    updateLevel(value);
    alert(formatMessage(value));
  }

  async function toggleListenForChanges() {
    isListening = listenForBatteryChanges((value) => {
      updateLevel(value);
    });
    if (isListening) {
      // update view binding right away
      const value = await checkBatteryLevel();
      updateLevel(value);
    }
  }

  function updateLevel(value: number) {
    level = value;
  }

  updateBatteryLevel();
</script>
